In [1]:
import numpy as np
import pandas as pd

In [2]:
#2. How to create a series from a list, numpy array and dict?
#Create a pandas series from each of the items below: a list, numpy and a dictionary

In [16]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myListSeries= pd.Series(mylist)
myarr = np.arange(26)
myArrSeries=pd.Series(myarr)
mydict = dict(zip(mylist, myarr))
myDicSeries=pd.Series(mydict)

In [15]:
#3. How to convert the index of a series into a column of a dataframe?
#Convert the series ser into a dataframe with its index as another column on the dataframe.

In [17]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [28]:
ser.to_frame().reset_index()

index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [29]:
#4. How to combine many series to form a dataframe?
#Combine ser1 and ser2 to form a dataframe.

In [30]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [37]:
pd.concat([ser1,ser2],axis=1)

0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [34]:
#5. How to assign name to the series’ index?
#Give a name to the series ser calling it ‘alphabets’.

pandas.core.frame.DataFrame

In [38]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [41]:
ser.name='Alphabet'

In [44]:
#6. How to get the items of series A not present in series B?
#From ser1 remove items present in ser2.

In [43]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [66]:
ser1[~ser1.isin(ser2)]

3    4
4    5
dtype: int64

In [67]:
#7. How to get the items not common to both series A and series B?
#Get all items of ser1 and ser2 not common to both.

In [68]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [73]:
(ser1[~ser1.isin(ser2)]).append(ser2[~ser2.isin(ser1)])

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

In [75]:
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [76]:
#8. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
#Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

In [80]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [79]:
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([-7.9140624 ,  4.6583193 ,  7.81129399, 10.09194277, 18.02400831])

In [82]:
#9. How to get frequency counts of unique items of a series?
#Calculte the frequency counts of each unique value ser.

In [83]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [93]:
ser.value_counts()

d    8
e    6
b    6
c    3
h    3
a    2
f    1
g    1
dtype: int64

In [94]:
#10. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
#From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.

In [143]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [148]:
ser[~ser.isin(ser.value_counts().head(2).index)]='others'

In [150]:
#11. How to bin a numeric series to 10 groups of equal size?
#Bin the series ser into 10 equal deciles and replace the values with the bin name.

In [151]:
ser = pd.Series(np.random.random(20))

In [155]:
pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'])

0      1st
1      4th
2      6th
3     10th
4     10th
5      5th
6      8th
7      5th
8      7th
9      6th
10     2nd
11     8th
12     9th
13     1st
14     4th
15     7th
16     9th
17     3rd
18     2nd
19     3rd
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [156]:
#12. How to convert a numpy array to a dataframe of given shape? (L1)
#Reshape the series ser into a dataframe with 7 rows and 5 columns

In [157]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [162]:
pd.DataFrame(ser.values.reshape(7,5),columns=["Column1","Column2","Column3","Column4","Column5"])

Column1  Column2  Column3  Column4  Column5
0        8        5        5        7        3
1        3        9        1        2        1
2        8        6        1        2        6
3        8        5        7        7        5
4        6        7        7        2        9
5        6        2        4        4        9
6        9        7        4        4        9

In [163]:
#13. How to find the positions of numbers that are multiples of 3 from a series?
#Find the positions of numbers that are multiples of 3 from ser.

In [169]:
ser = pd.Series(np.random.randint(1, 10, 7))

In [174]:
np.argwhere(ser.values % 3 == 0)

array([[1],
       [2],
       [4]])

In [175]:
#How to extract items at given positions from a series
#From ser, extract the items at positions in list pos.

In [176]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [180]:
ser[pos]
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [181]:
#15. How to stack two series vertically and horizontally ?
#Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

In [182]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [190]:
#vertical stack
ser1.append(ser2)#solution1
pd.concat([ser1,ser2],axis=0)#solution2

index  0
0      0  0
1      1  1
2      2  2
3      3  3
4      4  4
5      0  a
6      1  b
7      2  c
8      3  d
9      4  e

In [193]:
#Horizontal stack
pd.concat([ser1,ser2],axis=1)

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [194]:
#16. How to get the positions of items of series A in another series B?
#Get the positions of items of ser2 in ser1 as a list.

In [2]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [5]:
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [6]:
#17. How to compute the mean squared error on a truth and predicted series?
#Compute the mean squared error of truth and pred series.

In [7]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [8]:
np.mean((truth-pred)**2)

0.47603041844828964

In [9]:
#18. How to convert the first character of each element in a series to uppercase?
#Change the first character of each word to upper case in each word of ser.

In [10]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [20]:
[i[0].upper()+i[1:] for i in ser] #solution1

['How', 'To', 'Kick', 'Ass?']

In [21]:
ser.map(lambda x: x.title()) #solution2

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [22]:
ser.map(lambda i: i[0].upper()+i[1:]) #solution3

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [23]:
#19. How to calculate the number of characters in each word in a series?

In [27]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [28]:
[len(x) for x in ser] #solution1

[3, 2, 4, 4]

In [29]:
ser.map(lambda x: len(x)) #solution2

0    3
1    2
2    4
3    4
dtype: int64

In [30]:
#20. How to compute difference of differences between consequtive numbers of a series?
#Difference of differences between the consequtive numbers of ser.

In [31]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [43]:
ser.diff().tolist()

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

In [44]:
#21. How to convert a series of date-strings to a timeseries?

In [50]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [51]:
pd.DatetimeIndex(ser) # solution1

DatetimeIndex(['2010-01-01 00:00:00', '2011-02-02 00:00:00',
               '2012-03-03 00:00:00', '2013-04-04 00:00:00',
               '2014-05-05 00:00:00', '2015-06-06 12:20:00'],
              dtype='datetime64[ns]', freq=None)

In [52]:
# Solution 2
from dateutil.parser import parse
ser.map(lambda x: parse(x))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [53]:
#22. How to get the day of month, week number, day of year and day of week from a series of date strings?
#Get the day of month, week number, day of year and day of week from ser.

In [54]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [59]:
dates=pd.DatetimeIndex(ser)

In [68]:
list(dates.day)

[1, 2, 3, 4, 5, 6]

In [67]:
list(dates.weekofyear)

[53, 5, 9, 14, 19, 23]

In [66]:
list(dates.dayofyear)

[1, 33, 63, 94, 125, 157]

In [65]:
list(dates.dayofweek)

[4, 2, 5, 3, 0, 5]

In [69]:
#23. How to convert year-month string to dates corresponding to the 4th day of the month?
#Change ser to dates that start with 4th of the respective months.

In [70]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [77]:
ser.map(lambda x: '04 '+x)

0    04 Jan 2010
1    04 Feb 2011
2    04 Mar 2012
dtype: object

In [78]:
#24. How to filter words that contain atleast 2 vowels from a series?
#From ser, extract words that contain atleast 2 vowels.

In [75]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

DatetimeIndex(['2010-01-04', '2011-02-04', '2012-03-04'], dtype='datetime64[ns]', freq=None)

In [79]:
#25. How to filter valid emails from a series?
#Extract the valid emails from the series emails. The regex pattern for valid emails is provided as reference.

In [80]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [135]:
import re
matches=emails.str.findall(pattern,flags=re.IGNORECASE)
[x for x in matches if len(x)>0]

[['rameses@egypt.com'], ['matt@t.co'], ['narendra@modi.com']]

In [145]:
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [146]:
#26. How to get the mean of a series grouped by another series?
#Compute the mean of weights of each fruit.

In [150]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
weights.tolist()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [151]:
fruit.tolist()

['carrot',
 'banana',
 'apple',
 'apple',
 'apple',
 'apple',
 'apple',
 'apple',
 'carrot',
 'apple']

In [161]:
fruitsWights=pd.concat([fruit,weights],axis=1)

In [162]:
fruitsWights.groupby([0]).mean() # solution1

1
0               
apple   6.142857
banana  2.000000
carrot  5.000000

In [163]:
weights.groupby(fruit).mean() # solution2

apple     6.142857
banana    2.000000
carrot    5.000000
dtype: float64

In [166]:
#27. How to compute the euclidean distance between two series?
#Compute the euclidean distance between series (points) p and q, without using a packaged formula.

In [167]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [168]:
np.linalg.norm(p-q)

18.16590212458495

In [169]:
#28. How to find all the local maxima (or peaks) in a numeric series?
#Get the positions of peaks (values surrounded by smaller values on both sides) in ser.

In [170]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

In [171]:
np.diff(np.sign(np.diff(ser)))

array([-2,  2,  0,  0, -2,  2, -2])

In [172]:
#29. How to replace missing spaces in a string with the least frequent character?
#Replace the spaces in my_str with the least frequent character.

In [173]:
my_str = 'dbc deb abed gade'

In [174]:
my_str.replace(' ','c')

'dbccdebcabedcgade'

In [176]:
#30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that 
#having random numbers as values?

In [222]:
pd.Series(pd.date_range(start='2000-1-1',periods=10,freq='W-SAT'))

0   2000-01-01
1   2000-01-08
2   2000-01-15
3   2000-01-22
4   2000-01-29
5   2000-02-05
6   2000-02-12
7   2000-02-19
8   2000-02-26
9   2000-03-04
dtype: datetime64[ns]

In [223]:
#31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
#ser has missing dates and values. Make all missing dates appear and fill up with value from previous date.

In [224]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

In [234]:
pd.date_range(start=ser.index[0], end=ser.index[len(ser.index)-1],freq='D')

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [2]:
#32. How to compute the autocorrelations of a numeric series?
#Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.

In [4]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

In [7]:
[ser.autocorr(i).round(2) for i in range(11)]

[1.0, -0.04, 0.07, 0.17, 0.36, -0.4, 0.09, 0.39, 0.19, 0.04, -0.13]

In [8]:
#33. How to import only every nth row from a csv file to create a dataframe?
#Import every 50th row of BostonHousing dataset as a dataframe.

In [32]:
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',skiprows=[i for i in range(0,len(pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'))) if i%50!=0])

crim  zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0   0.21977   0   6.91     0  0.448  5.602  62.0  6.0877    3  233     17.9   
1   0.06860   0   2.89     0  0.445  7.416  62.5  3.4952    2  276     18.0   
2   2.73397   0  19.58     0  0.871  5.597  94.9  1.5257    5  403     14.7   
3   0.03150  95   1.47     0  0.403  6.975  15.3  7.6534    3  402     17.0   
4   0.19073  22   5.86     0  0.431  6.718  17.5  7.8265    7  330     19.1   
5   0.05561  70   2.24     0  0.400  7.041  10.0  7.8278    5  358     14.8   
6   0.02899  40   1.25     0  0.429  6.939  34.5  8.7921    1  335     19.7   
7   9.91655   0  18.10     0  0.693  5.852  77.8  1.5004   24  666     20.2   
8   7.52601   0  18.10     0  0.713  6.417  98.3  2.1850   24  666     20.2   
9   0.17783   0   9.69     0  0.585  5.569  73.5  2.3999    6  391     19.2   
10  0.04741   0  11.93     0  0.573  6.030  80.8  2.5050    1  273     21.0   

         b  lstat  medv  
0   396.90  16.20  19.4  
1   396.90   6.19  33.2  
2   351.85  21.45  15.4  
3   396.90   4.56  34.9  
4   393.74   6.56  26.2  
5   371.58   4.74  29.0  
6   389.85   5.89  26.6  
7   338.16  29.97   6.3  
8   304.21  19.31  13.0  
9   395.77  15.10  17.5  
10  396.90   7.88  11.9

In [83]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
df2

age       b  chas      crim     dis  indus  lstat  medv    nox  \
0     65.2  396.90   0.0   0.00632  4.0900   2.31   4.98  24.0  0.538   
50    45.7  395.56   0.0   0.08873  6.8147   5.64  13.45  19.7  0.439   
100   79.9  394.76   0.0   0.14866  2.7778   8.56   9.42  27.5  0.520   
150   97.3  372.80   0.0   1.65660  1.6180  19.58  14.10  21.5  0.871   
200   13.9  384.30   0.0   0.01778  7.6534   1.47   4.45  32.9  0.403   
250   13.0  396.28   0.0   0.14030  7.3967   5.86   5.90  24.4  0.431   
300   47.4  390.86   0.0   0.04417  7.8278   2.24   6.07  24.8  0.400   
350   44.4  396.90   0.0   0.06211  8.7921   1.25   5.98  22.9  0.429   
400  100.0  396.90   0.0  25.04610  1.5888  18.10  26.77   5.6  0.693   
450   92.6    0.32   0.0   6.71772  2.3236  18.10  17.44  13.4  0.713   
500   79.7  396.90   0.0   0.22438  2.4982   9.69  14.33  16.8  0.585   

     ptratio   rad     rm    tax    zn  
0       15.3   1.0  6.575  296.0  18.0  
50      16.8   4.0  5.963  243.0  21.0  
100     20.9   5.0  6.727  384.0   0.0  
150     14.7   5.0  6.122  403.0   0.0  
200     17.0   3.0  7.135  402.0  95.0  
250     19.1   7.0  6.487  330.0  22.0  
300     14.8   5.0  6.871  358.0  70.0  
350     19.7   1.0  6.490  335.0  40.0  
400     20.2  24.0  5.987  666.0   0.0  
450     20.2  24.0  6.749  666.0   0.0  
500     19.2   6.0  6.027  391.0   0.0

In [84]:
indexs=[i for i in range(0,len(pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'))) if i%50!=0]
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
df.drop(indexs)

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0     0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
50    0.08873  21.0   5.64     0  0.439  5.963   45.7  6.8147    4  243   
100   0.14866   0.0   8.56     0  0.520  6.727   79.9  2.7778    5  384   
150   1.65660   0.0  19.58     0  0.871  6.122   97.3  1.6180    5  403   
200   0.01778  95.0   1.47     0  0.403  7.135   13.9  7.6534    3  402   
250   0.14030  22.0   5.86     0  0.431  6.487   13.0  7.3967    7  330   
300   0.04417  70.0   2.24     0  0.400  6.871   47.4  7.8278    5  358   
350   0.06211  40.0   1.25     0  0.429  6.490   44.4  8.7921    1  335   
400  25.04610   0.0  18.10     0  0.693  5.987  100.0  1.5888   24  666   
450   6.71772   0.0  18.10     0  0.713  6.749   92.6  2.3236   24  666   
500   0.22438   0.0   9.69     0  0.585  6.027   79.7  2.4982    6  391   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  
250     19.1  396.28   5.90  24.4  
300     14.8  390.86   6.07  24.8  
350     19.7  396.90   5.98  22.9  
400     20.2  396.90  26.77   5.6  
450     20.2    0.32  17.44  13.4  
500     19.2  396.90  14.33  16.8

In [99]:
#34. How to change column values when importing csv to a dataframe?
#Import the boston housing dataset, but while importing change the 'medv' (median house value) column so that values < 25 becomes ‘Low’ and > 25 becomes ‘High’.

In [98]:
vgt=lambda x: (x.replace(x,'high') if float(x)>25 else x.replace(x,'low'))
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',converters={'medv':vgt})

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0     0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
1     0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242   
2     0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242   
3     0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222   
4     0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222   
5     0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222   
6     0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311   
7     0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311   
8     0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311   
9     0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   
10    0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5  311   
11    0.11747  12.5   7.87     0  0.524  6.009   82.9  6.2267    5  311   
12    0.09378  12.5   7.87     0  0.524  5.889   39.0  5.4509    5  311   
13    0.62976   0.0   8.14     0  0.538  5.949   61.8  4.7075    4  307   
14    0.63796   0.0   8.14     0  0.538  6.096   84.5  4.4619    4  307   
15    0.62739   0.0   8.14     0  0.538  5.834   56.5  4.4986    4  307   
16    1.05393   0.0   8.14     0  0.538  5.935   29.3  4.4986    4  307   
17    0.78420   0.0   8.14     0  0.538  5.990   81.7  4.2579    4  307   
18    0.80271   0.0   8.14     0  0.538  5.456   36.6  3.7965    4  307   
19    0.72580   0.0   8.14     0  0.538  5.727   69.5  3.7965    4  307   
20    1.25179   0.0   8.14     0  0.538  5.570   98.1  3.7979    4  307   
21    0.85204   0.0   8.14     0  0.538  5.965   89.2  4.0123    4  307   
22    1.23247   0.0   8.14     0  0.538  6.142   91.7  3.9769    4  307   
23    0.98843   0.0   8.14     0  0.538  5.813  100.0  4.0952    4  307   
24    0.75026   0.0   8.14     0  0.538  5.924   94.1  4.3996    4  307   
25    0.84054   0.0   8.14     0  0.538  5.599   85.7  4.4546    4  307   
26    0.67191   0.0   8.14     0  0.538  5.813   90.3  4.6820    4  307   
27    0.95577   0.0   8.14     0  0.538  6.047   88.8  4.4534    4  307   
28    0.77299   0.0   8.14     0  0.538  6.495   94.4  4.4547    4  307   
29    1.00245   0.0   8.14     0  0.538  6.674   87.3  4.2390    4  307   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
476   4.87141   0.0  18.10     0  0.614  6.484   93.6  2.3053   24  666   
477  15.02340   0.0  18.10     0  0.614  5.304   97.3  2.1007   24  666   
478  10.23300   0.0  18.10     0  0.614  6.185   96.7  2.1705   24  666   
479  14.33370   0.0  18.10     0  0.614  6.229   88.0  1.9512   24  666   
480   5.82401   0.0  18.10     0  0.532  6.242   64.7  3.4242   24  666   
481   5.70818   0.0  18.10     0  0.532  6.750   74.9  3.3317   24  666   
482   5.73116   0.0  18.10     0  0.532  7.061   77.0  3.4106   24  666   
483   2.81838   0.0  18.10     0  0.532  5.762   40.3  4.0983   24  666   
484   2.37857   0.0  18.10     0  0.583  5.871   41.9  3.7240   24  666   
485   3.67367   0.0  18.10     0  0.583  6.312   51.9  3.9917   24  666   
486   5.69175   0.0  18.10     0  0.583  6.114   79.8  3.5459   24  666   
487   4.83567   0.0  18.10     0  0.583  5.905   53.2  3.1523   24  666   
488   0.15086   0.0  27.74     0  0.609  5.454   92.7  1.8209    4  711   
489   0.18337   0.0  27.74     0  0.609  5.414   98.3  1.7554    4  711   
490   0.20746   0.0  27.74     0  0.609  5.093   98.0  1.8226    4  711   
491   0.10574   0.0  27.74     0  0.609  5.983   98.8  1.8681    4  711   
492   0.11132   0.0  27.74     0  0.609  5.983   83.5  2.1099    4  711   
493   0.17331   0.0   9.69     0  0.585  5.707   54.0  2.3817    6  391   
494   0.27957   0.0   9.69     0  0.585  5.926   42.6  2.3817    6  391   
495   0.17899   0.0   9.69     0  0.585  5.670   28.8  2.7986    6  391   
496   0.28960   0.0   9.69     0  0.585  5.390   72.9  2.7986    6  391   
497   0.26838   0.0   9.69     0  

In [100]:
#35. How to create a dataframe with rows as strides from a given series?

In [101]:
L = pd.Series(range(15))

In [103]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [104]:
#36. How to import only specified columns from a csv file?
#Import ‘crim’ and ‘medv’ columns of the BostonHousing dataset as a dataframe.

In [107]:
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',usecols=['crim','medv'])

crim  medv
0     0.00632  24.0
1     0.02731  21.6
2     0.02729  34.7
3     0.03237  33.4
4     0.06905  36.2
5     0.02985  28.7
6     0.08829  22.9
7     0.14455  27.1
8     0.21124  16.5
9     0.17004  18.9
10    0.22489  15.0
11    0.11747  18.9
12    0.09378  21.7
13    0.62976  20.4
14    0.63796  18.2
15    0.62739  19.9
16    1.05393  23.1
17    0.78420  17.5
18    0.80271  20.2
19    0.72580  18.2
20    1.25179  13.6
21    0.85204  19.6
22    1.23247  15.2
23    0.98843  14.5
24    0.75026  15.6
25    0.84054  13.9
26    0.67191  16.6
27    0.95577  14.8
28    0.77299  18.4
29    1.00245  21.0
..        ...   ...
476   4.87141  16.7
477  15.02340  12.0
478  10.23300  14.6
479  14.33370  21.4
480   5.82401  23.0
481   5.70818  23.7
482   5.73116  25.0
483   2.81838  21.8
484   2.37857  20.6
485   3.67367  21.2
486   5.69175  19.1
487   4.83567  20.6
488   0.15086  15.2
489   0.18337   7.0
490   0.20746   8.1
491   0.10574  13.6
492   0.11132  20.1
493   0.17331  21.8
494   0.27957  24.5
495   0.17899  23.1
496   0.28960  19.7
497   0.26838  18.3
498   0.23912  21.2
499   0.17783  17.5
500   0.22438  16.8
501   0.06263  22.4
502   0.04527  20.6
503   0.06076  23.9
504   0.10959  22.0
505   0.04741  11.9

[506 rows x 2 columns]

In [108]:
#37. How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.
#Get the number of rows, columns, datatype and summary statistics of each column of the Cars93 dataset. Also get the numpy array and list equivalent of the dataframe.

In [110]:
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [124]:
df.shape

(93, 27)

In [120]:
df.describe()

Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

In [122]:
df.get_dtype_counts()

float64    18
object      9
dtype: int64

In [129]:
df.values

array([['Acura', 'Integra', 'Small', ..., 2705.0, 'non-USA',
        'Acura Integra'],
       [nan, 'Legend', 'Midsize', ..., 3560.0, 'non-USA', 'Acura Legend'],
       ['Audi', '90', 'Compact', ..., 3375.0, 'non-USA', 'Audi 90'],
       ...,
       ['Volkswagen', 'Corrado', 'Sporty', ..., 2810.0, 'non-USA',
        'Volkswagen Corrado'],
       ['Volvo', '240', 'Compact', ..., 2985.0, 'non-USA', 'Volvo 240'],
       [nan, '850', 'Midsize', ..., 3245.0, 'non-USA', 'Volvo 850']],
      dtype=object)

In [131]:
df.values.tolist()

[['Acura',
  'Integra',
  'Small',
  12.9,
  15.9,
  18.8,
  25.0,
  31.0,
  'None',
  'Front',
  '4',
  1.8,
  140.0,
  6300.0,
  2890.0,
  'Yes',
  13.2,
  5.0,
  177.0,
  102.0,
  68.0,
  37.0,
  26.5,
  nan,
  2705.0,
  'non-USA',
  'Acura Integra'],
 [nan,
  'Legend',
  'Midsize',
  29.2,
  33.9,
  38.7,
  18.0,
  25.0,
  'Driver & Passenger',
  'Front',
  '6',
  3.2,
  200.0,
  5500.0,
  2335.0,
  'Yes',
  18.0,
  5.0,
  195.0,
  115.0,
  71.0,
  38.0,
  30.0,
  15.0,
  3560.0,
  'non-USA',
  'Acura Legend'],
 ['Audi',
  '90',
  'Compact',
  25.9,
  29.1,
  32.3,
  20.0,
  26.0,
  'Driver only',
  'Front',
  '6',
  2.8,
  172.0,
  5500.0,
  2280.0,
  'Yes',
  16.9,
  5.0,
  180.0,
  102.0,
  67.0,
  37.0,
  28.0,
  14.0,
  3375.0,
  'non-USA',
  'Audi 90'],
 ['Audi',
  '100',
  'Midsize',
  nan,
  37.7,
  44.6,
  19.0,
  26.0,
  'Driver & Passenger',
  nan,
  '6',
  nan,
  172.0,
  5500.0,
  2535.0,
  nan,
  21.1,
  6.0,
  193.0,
  106.0,
  nan,
  37.0,
  31.0,
  17.0,
  3405.0,


In [132]:
#38. How to extract the row and column number of a particular cell with given criterion?
#Which manufacturer, model and type has the highest Price? What is the row and column number of the cell with the highest Price value?

In [144]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [197]:
df.loc[df.Price==np.max(df.Price),['Manufacturer', 'Model', 'Type']]
row,col=np.where(df.values==np.max(df.Price))
df.iloc[row[0]]

Manufacturer               Mercedes-Benz
Model                               300E
Type                             Midsize
Min.Price                           43.8
Price                               61.9
Max.Price                             80
MPG.city                              19
MPG.highway                           25
AirBags               Driver & Passenger
DriveTrain                          Rear
Cylinders                              6
EngineSize                           3.2
Horsepower                           217
RPM                                 5500
Rev.per.mile                        2220
Man.trans.avail                       No
Fuel.tank.capacity                  18.5
Passengers                             5
Length                               NaN
Wheelbase                            110
Width                                 69
Turn.circle                           37
Rear.seat.room                       NaN
Luggage.room                          15
Weight          

In [206]:
#39. How to rename a specific columns in a dataframe?
#Rename the column Type as CarType in df and replace the ‘.’ in column names with ‘_’.

In [211]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [213]:
df.rename(columns={'Type':'CarType'})

Manufacturer          Model  CarType  Min.Price  Price  Max.Price  \
0         Acura        Integra    Small       12.9   15.9       18.8   
1           NaN         Legend  Midsize       29.2   33.9       38.7   
2          Audi             90  Compact       25.9   29.1       32.3   
3          Audi            100  Midsize        NaN   37.7       44.6   
4           BMW           535i  Midsize        NaN   30.0        NaN   
5         Buick        Century  Midsize       14.2   15.7       17.3   
6         Buick        LeSabre    Large       19.9   20.8        NaN   
7         Buick     Roadmaster    Large       22.6   23.7       24.9   
8         Buick        Riviera  Midsize       26.3   26.3       26.3   
9      Cadillac        DeVille    Large       33.0   34.7       36.3   
10     Cadillac        Seville  Midsize       37.5   40.1       42.7   
11    Chevrolet       Cavalier  Compact        8.5   13.4       18.3   
12    Chevrolet        Corsica  Compact       11.4   11.4       11.4   
13    Chevrolet         Camaro   Sporty       13.4   15.1       16.8   
14    Chevrolet         Lumina  Midsize       13.4   15.9       18.4   
15    Chevrolet     Lumina_APV      Van       14.7   16.3       18.0   
16    Chevrolet          Astro      Van       14.7   16.6       18.6   
17    Chevrolet        Caprice    Large       18.0   18.8       19.6   
18    Chevrolet       Corvette   Sporty       34.6   38.0       41.5   
19          NaN       Concorde    Large       18.4   18.4       18.4   
20     Chrysler        LeBaron  Compact       14.5   15.8       17.1   
21     Chrysler       Imperial    Large       29.5   29.5       29.5   
22        Dodge           Colt    Small        7.9    9.2       10.6   
23        Dodge         Shadow    Small        8.4   11.3       14.2   
24        Dodge         Spirit  Compact       11.9   13.3       14.7   
25        Dodge        Caravan      Van        NaN   19.0       24.4   
26        Dodge        Dynasty  Midsize       14.8   15.6       16.4   
27        Dodge        Stealth   Sporty       18.5   25.8       33.1   
28        Eagle         Summit    Small        7.9   12.2       16.5   
29        Eagle         Vision    Large        NaN   19.3       21.2   
..          ...            ...      ...        ...    ...        ...   
63       Nissan         Sentra    Small        8.7   11.8       14.9   
64       Nissan         Altima  Compact       13.0   15.7       18.3   
65       Nissan          Quest      Van       16.7   19.1       21.5   
66       Nissan         Maxima  Midsize       21.0   21.5       22.0   
67   Oldsmobile        Achieva  Compact       13.0   13.5       14.0   
68   Oldsmobile  Cutlass_Ciera  Midsize       14.2   16.3       18.4   
69   Oldsmobile     Silhouette      Van       19.5   19.5       19.5   
70   Oldsmobile   Eighty-Eight    Large       19.5   20.7       21.9   
71     Plymouth          Laser   Sporty       11.4   14.4       17.4   
72      Pontiac         LeMans    Small        NaN    9.0        9.9   
73      Pontiac        Sunbird  Compact        9.4   11.1       12.8   
74      Pontiac       Firebird      NaN       14.0   17.7       21.4   
75      Pontiac     Grand_Prix  Midsize       15.4   18.5       21.6   
76      Pontiac     Bonneville    Large       19.4   24.4       29.4   
77         Saab            900  Compact       20.3   28.7       37.1   
78       Saturn             SL    Small        9.2    NaN       12.9   
79       Subaru          Justy    Small        7.3    8.4        9.5   
80       Subaru         Loyale    Small       10.5   10.9       11.3   
81       Subaru         Legacy  Compact       16.3   19.5       22.7   
82       Suzuki          Swift      NaN        7.3    8.6        NaN   
83       Toyota         Tercel    Small        NaN    9.8       11.8   
84       Toyota         Celica   Sporty       14.2   18.4       22.6   
85       Toyota          Camry  Midsize       15.2    NaN       21.2   
86       Toyota         Previa      Van    

In [214]:
df.columns.map(lambda x: x.replace('.','_'))

Index(['Manufacturer', 'Model', 'Type', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [215]:
#40. How to check if a dataframe has any missing values?
#Check if df has any missing values.

In [216]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [221]:
df.isna().values.any()

True

In [222]:
#41. How to count the number of missing values in each column?
#Count the number of missing values in each column of df. Which column has the maximum number of missing values?

In [223]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [272]:
nullCounts=df.apply(lambda x: x.isnull().values.sum())

In [292]:
nullCounts.index[nullCounts.values.argmax()]

'Luggage.room'

In [293]:
#42. How to replace missing values of multiple numeric columns with the mean?
#Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [294]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [353]:
#solution1
df['Min.Price']=[np.mean(df['Min.Price']) if np.isnan(i)==True else i for i in df['Min.Price'].values]
df['Max.Price']=[np.mean(df['Max.Price']) if np.isnan(i)==True else i for i in df['Max.Price'].values]

In [369]:
#solution2 
df[['Min.Price', 'Max.Price']]=df[['Min.Price', 'Max.Price']].apply(lambda x:x.fillna(x.mean()))

In [362]:
#43. How to use apply function on existing columns with global variables as additional arguments?
#In df, use apply method to replace the missing values in Min.Price with the column’s mean and those in Max.Price with the column’s median.

In [378]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price']=df[['Min.Price']].apply(lambda x: x.fillna(x.mean()))

In [379]:
df['Max.Price']=df[['Max.Price']].apply(lambda x: x.fillna(x.median()))

In [380]:
df

Manufacturer          Model     Type  Min.Price  Price  Max.Price  \
0         Acura        Integra    Small  12.900000   15.9      18.80   
1           NaN         Legend  Midsize  29.200000   33.9      38.70   
2          Audi             90  Compact  25.900000   29.1      32.30   
3          Audi            100  Midsize  17.118605   37.7      44.60   
4           BMW           535i  Midsize  17.118605   30.0      19.15   
5         Buick        Century  Midsize  14.200000   15.7      17.30   
6         Buick        LeSabre    Large  19.900000   20.8      19.15   
7         Buick     Roadmaster    Large  22.600000   23.7      24.90   
8         Buick        Riviera  Midsize  26.300000   26.3      26.30   
9      Cadillac        DeVille    Large  33.000000   34.7      36.30   
10     Cadillac        Seville  Midsize  37.500000   40.1      42.70   
11    Chevrolet       Cavalier  Compact   8.500000   13.4      18.30   
12    Chevrolet        Corsica  Compact  11.400000   11.4      11.40   
13    Chevrolet         Camaro   Sporty  13.400000   15.1      16.80   
14    Chevrolet         Lumina  Midsize  13.400000   15.9      18.40   
15    Chevrolet     Lumina_APV      Van  14.700000   16.3      18.00   
16    Chevrolet          Astro      Van  14.700000   16.6      18.60   
17    Chevrolet        Caprice    Large  18.000000   18.8      19.60   
18    Chevrolet       Corvette   Sporty  34.600000   38.0      41.50   
19          NaN       Concorde    Large  18.400000   18.4      18.40   
20     Chrysler        LeBaron  Compact  14.500000   15.8      17.10   
21     Chrysler       Imperial    Large  29.500000   29.5      29.50   
22        Dodge           Colt    Small   7.900000    9.2      10.60   
23        Dodge         Shadow    Small   8.400000   11.3      14.20   
24        Dodge         Spirit  Compact  11.900000   13.3      14.70   
25        Dodge        Caravan      Van  17.118605   19.0      24.40   
26        Dodge        Dynasty  Midsize  14.800000   15.6      16.40   
27        Dodge        Stealth   Sporty  18.500000   25.8      33.10   
28        Eagle         Summit    Small   7.900000   12.2      16.50   
29        Eagle         Vision    Large  17.118605   19.3      21.20   
..          ...            ...      ...        ...    ...        ...   
63       Nissan         Sentra    Small   8.700000   11.8      14.90   
64       Nissan         Altima  Compact  13.000000   15.7      18.30   
65       Nissan          Quest      Van  16.700000   19.1      21.50   
66       Nissan         Maxima  Midsize  21.000000   21.5      22.00   
67   Oldsmobile        Achieva  Compact  13.000000   13.5      14.00   
68   Oldsmobile  Cutlass_Ciera  Midsize  14.200000   16.3      18.40   
69   Oldsmobile     Silhouette      Van  19.500000   19.5      19.50   
70   Oldsmobile   Eighty-Eight    Large  19.500000   20.7      21.90   
71     Plymouth          Laser   Sporty  11.400000   14.4      17.40   
72      Pontiac         LeMans    Small  17.118605    9.0       9.90   
73      Pontiac        Sunbird  Compact   9.400000   11.1      12.80   
74      Pontiac       Firebird      NaN  14.000000   17.7      21.40   
75      Pontiac     Grand_Prix  Midsize  15.400000   18.5      21.60   
76      Pontiac     Bonneville    Large  19.400000   24.4      29.40   
77         Saab            900  Compact  20.300000   28.7      37.10   
78       Saturn             SL    Small   9.200000    NaN      12.90   
79       Subaru          Justy    Small   7.300000    8.4       9.50   
80       Subaru         Loyale    Small  10.500000   10.9      11.30   
81       Subaru         Legacy  Compact  16.300000   19.5      22.70   
82       Suzuki          Swift      NaN   7.300000    8.6      19.15   
83       Toyota         Tercel    Small  17.118605    9.8      11.80   
84       Toyota         Celica   Sporty  14.200000   18.4      22.60   
85       Toyota          Camry  Midsize  15.200000    NaN      21.20   
86       Toyota         Previa      Van  17

In [385]:
#44. How to select a specific column from a dataframe as a dataframe instead of a series?
#Get the first column (a) in df as a dataframe (rather than as a Series).
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [395]:
pd.DataFrame((df['a']))

pandas.core.frame.DataFrame

In [409]:
type(df[['a']])# column inside two braces returns DataFrame, inside one brace return sseries 

pandas.core.frame.DataFrame

In [412]:
df.loc[:, 'a']# column inside two braces returns DataFrame, inside one brace return sseries.
#The frist argument is the rows, second argument is the columns

0     0
1     5
2    10
3    15
Name: a, dtype: int64

In [414]:
df.iloc[:, [1]]

b
0   1
1   6
2  11
3  16

In [415]:
#45. How to change the order of columns of a dataframe?
#Actually 3 questions.

#In df, interchange columns 'a' and 'c'.
#Create a generic function to interchange two columns, without hardcoding column names.

#Sort the columns in reverse alphabetical order, that is colume 'e' first through column 'a' last.

In [469]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [470]:
df


a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [468]:
tempcolumn=tuple(df['c'])
df['c']=df['a']
df['a']=tempcolumn
df.rename(columns={'c':'a','a':'c'})
df[df.columns[::-1]]

e   d   c   b   a
0   4   3   0   1   2
1   9   8   5   6   7
2  14  13  10  11  12
3  19  18  15  16  17

In [472]:
df.sort_index(axis=1, ascending=False, inplace=True)# the name of rows and columns are named Index

In [484]:
#46. How to set the number of rows and columns displayed in the output?
#Change the pamdas display settings on printing the dataframe df it shows a maximum of 10 rows and 10 columns.

In [495]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [497]:
#df[:10:][:10:]
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [498]:
#47. How to format or suppress scientific notations in a pandas dataframe?
#Suppress scientific notations like ‘e-03’ in df and print upto 4 numbers after decimal.

In [499]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

In [501]:
#solution 1
df.round(4)

random
0  0.6729
1  0.0000
2  0.0000
3  0.0000

In [502]:
#solution 2
df.apply(lambda x: '%.4f' % x, axis=1)

0    0.6729
1    0.0000
2    0.0000
3    0.0000
dtype: object

In [503]:
#48. How to format all the values in a dataframe as percentages?
#Format the values in column 'random' of df as percentages.

In [504]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

random
0  0.881899
1  0.144764
2  0.214509
3  0.517847

In [531]:
#solution 1
df.applymap(lambda x: str(np.round(x*100,2))+'%')

random
0  88.19%
1  14.48%
2  21.45%
3  51.78%

In [532]:
#solution 2
df.style.format({
    'random': '{0:.2%}'.format,
})

In [ ]:
#49. How to filter every nth row in a dataframe?
#From df, filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [533]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [536]:
#solution 1
df[['Manufacturer','Model','Type']][::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [537]:
#solution 2
df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [538]:
#50. How to create a primary key index by combining relevant columns?
#In df, Replace NaNs with ‘missing’ in columns 'Manufacturer', 'Model' and 'Type' and create a index as a combination of these three columns and check if the index is a primary key.

In [604]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
df

Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small       12.9       18.8
1           NaN   Legend  Midsize       29.2       38.7
2          Audi       90  Compact       25.9       32.3
3          Audi      100  Midsize        NaN       44.6
4           BMW     535i  Midsize        NaN        NaN
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van       16.6       22.7
89   Volkswagen   Passat  Compact       17.6       22.4
90   Volkswagen  Corrado   Sporty       22.9       23.7
91        Volvo      240  Compact       21.8       23.5
92          NaN      850  Midsize       24.8       28.5

[93 rows x 5 columns]

In [607]:
df.fillna(value={'Manufacturer':'missing','Model':'missing','Type':'missing'}).set_index(['Manufacturer','Model','Type'])

RangeIndex(start=0, stop=93, step=1)

In [608]:
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df['Manufacturer'] + '_' + df.Model + '_' + df.Type

In [610]:
df.index.is_unique

True

In [611]:
#51. How to get the row number of the nth largest value in a column?
#Find the row position of the 5th largest value of column 'a' in df.

In [652]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

In [656]:
indexofNumber=df['a'].loc[lambda x: x==np.sort(df['a'])[-5]].index

In [660]:
indexofNumber.values

array([3])

In [661]:
#52. How to find the position of the nth largest value greater than a given value?
#In ser, find the position of the 2nd largest value greater than the mean.

In [662]:
ser = pd.Series(np.random.randint(1, 100, 15))

In [697]:
ser.sort_values()[lambda x: x>ser.mean()].index[-2]

6

In [701]:
np.argwhere(ser>ser.mean())[1]

array([4])

In [702]:
#53. How to get the last n rows of a dataframe with row sum > 100?
#Get the last two rows of df whose row sum is greater than 100.

In [703]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [733]:
#solution 1
sums=df.aggregate("sum",axis=1)

#solution2
sums = df.apply(np.sum, axis=1)

In [734]:
np.where(sums>100)[0][-2:]

array([11, 12])

In [735]:
#54. How to find and cap outliers from a series or dataframe column?
#Replace all values of ser in the lower 5%ile and greater than 95%ile with respective 5th and 95th %ile value.

In [767]:
ser = pd.Series(np.logspace(-2, 2, 30))

In [745]:
ser.map(lambda x: '5th 'if x<5 else x)
ser.map(lambda x: '95th 'if x>95 else x)

0          0.01
1     0.0137382
2     0.0188739
3     0.0259294
4     0.0356225
        ...    
25      28.0722
26      38.5662
27      52.9832
28      72.7895
29        95th 
Length: 30, dtype: object

In [769]:
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934


In [773]:
#55. How to reshape a dataframe to the largest possible square after removing the negative values?
#Reshape df to the largest possible square with negative values removed. Drop the smallest values if need be. The order of the positive numbers in the result should remain the same as the original.

In [838]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

In [944]:
df.values

array([[ 47,  36,   5,  42,  -5,  12,  47, -12,  39,  45],
       [ 12,  22,  18,  41, -11,  20, -11,  37,   4,  -7],
       [ 14, -10,  26,  -5,  34,  -7,  14,  48, -13,   7],
       [-11,   1, -12,  33,   3,  24,  17,  23,  30,  43],
       [ -6,  33, -14,  35,  44,  37,  30,  -6,  13, -12],
       [ 14, -16,  26, -17,  17,  -4, -17, -13,   8,  -2],
       [  3,  39,  42,  23,  44, -11,   5,  15,  39,   6],
       [ 28,  11,   5,   0,  34,  24,  -7, -17, -14,   0],
       [ 34,   1,  19,  22, -19, -16,  20,  31,  -1,  -1],
       [ 46,  21,  -4,  25,  29, -13,  25,   8,  47,  19]])

In [889]:
postivearray=df.values[df.values>0]
array= postivearray[~ np.isnan(postivearray)]

array([47, 36,  5, 42, 12, 47, 39, 45, 12, 22, 18, 41, 20, 37,  4, 14, 26,
       34, 14, 48,  7,  1, 33,  3, 24, 17, 23, 30, 43, 33, 35, 44, 37, 30,
       13, 14, 26, 17,  8,  3, 39, 42, 23, 44,  5, 15, 39,  6, 28, 11,  5,
       34, 24, 34,  1, 19, 22, 20, 31, 46, 21, 25, 29, 25,  8, 47, 19])

In [942]:
# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square--> get sqrt and get the integer value
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n,-1)
print(output)

[[47. 36.  5. 42. 12. 47. 39. 45.]
 [12. 22. 18. 41. 20. 37.  4. 14.]
 [26. 34. 14. 48.  7. 33. 24. 17.]
 [23. 30. 43. 33. 35. 44. 37. 30.]
 [13. 14. 26. 17.  8.  3. 39. 42.]
 [23. 44.  5. 15. 39.  6. 28. 11.]
 [ 5. 34. 24. 34. 19. 22. 20. 31.]
 [46. 21. 25. 29. 25.  8. 47. 19.]]


In [945]:
#56. How to swap two rows of a dataframe?
#Swap rows 1 and 2 in df.

In [957]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [960]:
def swap_rows(df,i,j):
    a,b= df.iloc[i].copy(),df.iloc[j].copy()
    df.iloc[i],df.iloc[j]=b,a
    return df

In [961]:
swap_rows(df,1,2)

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

In [962]:
#57. How to reverse the rows of a dataframe?
#Reverse all the rows of dataframe df.

In [963]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [974]:
df.iloc[::-1]

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [975]:
#58. How to create one-hot encodings of a categorical variable (dummy variables)?
#Get one-hot encodings for column 'a' in the dataframe df and append it as columns.

In [1013]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

In [1014]:
columna=df['a'].copy()

In [1022]:
encoded=pd.get_dummies(columna.values)

In [1026]:
pd.concat([encoded,df],axis=1)

0  5  10  15  20   b   c   d   e   a
0  1  0   0   0   0   1   2   3   4   0
1  0  1   0   0   0   6   7   8   9   5
2  0  0   1   0   0  11  12  13  14  10
3  0  0   0   1   0  16  17  18  19  15
4  0  0   0   0   1  21  22  23  24  20

In [1027]:
pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [1028]:
#59. Which column contains the highest number of row-wise maximum values?
#Obtain the column name with the highest number of row-wise maximum’s in df.

In [1029]:
#61. How to know the maximum possible correlation value of each column against other columns?
#Compute maximum possible absolute correlation value of each column against other columns in df.

In [1030]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

In [1037]:
abscorr=abs(df.corr())

In [1040]:
abscorr.apply(lambda x: sorted(x)[-2])

p    0.687178
q    0.539405
r    0.561059
s    0.561059
t    0.670367
u    0.850541
v    0.453325
w    0.539405
x    0.850541
y    0.746747
dtype: float64

In [1041]:
#62. How to create a column containing the minimum by maximum of each row?
#Compute the minimum-by-maximum for every row of df.

In [1042]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [1077]:
df

0   1   2   3   4   5   6   7   8   9
0  21  70  62  64  45  18  50   9  48  17
1  36  95  55  18  29  26  27  81  28  20
2  51  87  39   6  63  95  69  23  14   8
3  16  90  47  24  95  86  63  29  22  77
4  13  44  39  73  49   6  89   6  40  38
5  74  55  54  42  68  89  24   5  12  71
6  53   9  27  46  38  61  53  44  24   7
7  53  93  93  32  17  81  34   6  40  29

In [1079]:
#solution 1
df.transpose().apply(lambda x: np.min(x)/np.max(x))
#solution 2
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

0    0.128571
1    0.189474
2    0.063158
3    0.168421
4    0.067416
5    0.056180
6    0.114754
7    0.064516
dtype: float64

In [1082]:
#63. How to create a column that contains the penultimate value in each row?
#Create a new column 'penultimate' which has the second largest value of each row of df.

In [1155]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [1154]:
#solution 1
df['penultimate']=np.transpose(df).apply(lambda x: sorted(x)[-2])

In [1156]:
#Solution 2
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate']=out

In [1158]:
#64. How to normalize all columns in a dataframe?
#Normalize all columns of df by subtracting the column mean and divide by standard deviation.
#Range all columns of df such that the minimum value in each column is 0 and max is 1.

In [1199]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [1201]:
df.apply(lambda x: ((x - x.mean())/x.std()).round(2),axis=0)

0     1     2     3     4     5     6     7     8     9
0 -0.55  0.53  1.21 -1.52 -0.23  1.18  0.22  0.06 -0.19 -0.95
1  1.66 -0.15 -0.23  0.90  0.45 -1.14  1.04  0.74  0.60  1.57
2 -0.83  1.71 -0.08  1.62 -1.76 -0.35 -1.69  0.84  1.51 -1.15
3  0.33 -1.23 -0.88  0.34 -0.74 -1.14  0.22 -0.78 -0.94  0.70
4  0.89  0.17 -1.16  0.07  0.73  0.45 -1.05 -1.86  1.19 -0.71
5 -1.29 -0.22  1.21 -1.02 -0.40 -0.18  1.27 -0.34 -0.19  0.49
6  0.47 -1.37  0.93 -0.31  1.46 -0.40 -0.37  1.24 -0.84  0.76
7 -0.69  0.56 -1.00 -0.08  0.50  1.58  0.36  0.10 -1.14 -0.71

In [1202]:
#65. How to compute the correlation of each row with the suceeding row?
#Compute the correlation of each row of df with its succeeding row.

In [1203]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [1210]:
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[0.14, -0.41, 0.61, -0.48, 0.27, 0.3, -0.67]

In [1211]:
#66. How to replace both the diagonals of dataframe with 0?
#Replace both values in both diagonals of df with 0.

In [1308]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

In [1310]:
#solution 1
np.fill_diagonal(np.fliplr(df),0)
np.fill_diagonal(df.values,0)

In [ ]:
#solution 2
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0

In [1313]:
#67. How to get the particular group of a groupby dataframe by key?
#This is a question related to understanding of grouped dataframe. From df_grouped, get the group belonging to 'apple' as a dataframe.

In [1314]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

In [1349]:
df.groupby('col1').get_group('apple')

col1      col2  col3
0  apple  0.967249    13
3  apple  0.284793    10
6  apple  0.920081    13

In [1353]:
#68. How to get the n’th largest value of a column when grouped by another column?
#In df, find the second largest value of 'taste' for 'banana'

In [1378]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

In [1379]:
fruitgroup=df.groupby('fruit')

In [1381]:
bananagroup=fruitgroup.get_group('banana')

In [1382]:
sorted(bananagroup['taste'])[-2]

0.5043144991644025

In [1383]:
#69. How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?
#In df, Compute the mean price of every fruit, while keeping the fruit as another column instead of an index.

In [1397]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

In [1403]:
df.groupby(by='fruit',as_index=False)['price'].mean()

fruit      price
0   apple   7.666667
1  banana   6.666667
2  orange  10.333333

In [1404]:
#70. How to join two dataframes by 2 columns so they have only the common rows?
#Join dataframes df1 and df2 by ‘fruit-pazham’ and ‘weight-kilo’.

In [1405]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

In [1427]:
df1.merge(df2,left_on=['fruit', 'weight'],right_on=['pazham', 'kilo'],suffixes=('_left','_right'))

fruit weight  price_left  pazham  kilo  price_right
0   apple   high          14   apple  high            1
1   apple   high          13   apple  high            1
2   apple   high           8   apple  high            1
3  orange    low           3  orange   low           11
4  orange    low           1  orange   low           11
5  orange    low           1  orange   low           11

In [1428]:
#71. How to remove rows from a dataframe that are present in another dataframe?
#From df1, remove the rows that are present in df2. All three columns must be the same.

In [1560]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

In [1562]:
df1[~df1.isin(df2).all(1)]

fruit  weight  price
0   apple    high      7
1  banana  medium      4
2  orange     low      5
3   apple    high      4
4  banana  medium     13
5  orange     low      9
6   apple    high      3
7  banana  medium      1
8  orange     low     14

In [1565]:
#72. How to get the positions where values of two columns match?

In [1566]:
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

In [1571]:
#solution1
df[lambda x: x['fruit1']==x['fruit2']].index

Int64Index([4, 9], dtype='int64')

In [1573]:
#solution2
np.where(df['fruit1']==df['fruit2'])

(array([4, 9]),)

In [1574]:
#73. How to create lags and leads of a column in a dataframe?
#Create two new columns in df, one of which is a lag1 (shift column a down by 1 row) of column ‘a’ and the other is a lead1 (shift column b up by 1 row).

In [1575]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

In [1577]:
df['lag1']=df['a'].shift(periods=1)

In [1579]:
df['lead1']=df['b'].shift(periods=-1)

In [1581]:
#74. How to get the frequency of unique values in the entire dataframe?
#Get the frequency of unique values in the entire dataframe df.

In [1583]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

In [1592]:
pd.value_counts(df.values.ravel())

4    5
8    3
5    3
2    3
9    2
1    2
6    1
3    1
dtype: int64

In [1596]:
#75. How to split a text column into two separate columns?
#Split the string column in df to form a dataframe with 3 columns as shown.

In [1667]:
df = pd.DataFrame(["STD, City;State",
"33, Kolkat;West Bengal",
"44, Chennai;Tamil Nadu",
"40, Hyderabad;Telengana",
"80, Bangalore;Karnataka"], columns=['row'])

In [1668]:
out=df.row.str.split(',|;', expand=True)

In [1670]:
out.columns=out.iloc[0]

In [1671]:
out=out[1:]

In [1672]:
out

0 STD        City        State
1  33      Kolkat  West Bengal
2  44     Chennai   Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka

'/Users/mohammaddaneshkohan'